##---------------------------------------------------------------------##
# Simulation parameters
uav_platoon:
  patrol_nodes: [38, 51]
  initial_nodes_pos: [38, 51, 37]
  patrolling_node: [1]

ugv_platoon:
  patrol_nodes: [38, 51]
  initial_nodes_pos: [38, 51, 37]
  patrolling_node: [1]

##---------------------------------------------------------------------##
# Parameter fields
uav:
  primitive: 'formation'
  n_vehicles: 10
  target_pos: [20, 100]
  vehicles_id: []
  vehicles_type: 'uav'
  vehicles: []
  centroid_pos: [-10, -10]
  platoon_id: 0
  initial_formation: True
  selected: False
  execute: True
  with_in_perimeter: False
##---------------------------------------------------------------------##
ugv:
  primitive: 'formation'
  n_vehicles: 8
  target_pos: [20, 100]
  vehicles_id: []
  vehicles_type: 'ugv'
  vehicles: []
  centroid_pos: [-10, -10]
  platoon_id: 0
  initial_formation: True
  selected: False
  execute: True
  with_in_perimeter: False
##---------------------------------------------------------------------##
